### ISSUE TITLE
[Errno 2] No such file or directory: 'xwininfo': 'xwininfo'

### ISSUE THREAD

**Issue by biographie** [calandoa/movescreen#10]
I'm getting the following error for some reason:
Traceback (most recent call last):
  File "/usr/local/bin/movescreen.py", line 86, in <module>
    out = subprocess.check_output(['xwininfo', '-id', id, '-all']).decode('ascii', 'ignore')
  File "/home/biographie/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/biographie/anaconda3/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/biographie/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/biographie/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xwininfo': 'xwininfo'

I have installed xwininfo and tried re-running the command, but still getting this error

**Comment by JustAlternate** [comment]
you have to install wmctrl aswell

`pacman -S wmctrl`
