### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'xwininfo'

### ISSUE THREAD

**Issue by msoutopico** [calandoa/movescreen#14]
I have installed the script in EndeavourOS (arch-based distro), running XFCE.

I noticed the shortcuts weren't working, so I tried to run it in the terminal, and I got:

```
 /usr/local/bin  movescreen.py right
Traceback (most recent call last):
  File "/usr/local/bin/movescreen.py", line 95, in <module>
    out = subprocess.check_output(['xwininfo', '-id', id, '-all']).decode('ascii', 'ignore')
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xwininfo'
``` 

I hope that helps.
Great script, btw.

**Comment by ajgringo619** [comment]
Had the same exact problem after I rebuilt my system last week. Try this: `yay -S xorg-xwininfo wmctrl`

**Comment by msoutopico** [comment]
> yay -S xorg-xwininfo wmctrl

It works, thanks a lot. I couldn't find package `xwininfo`. Cheers!

**Comment by ajgringo619** [comment]
Here's an example of how to find which packages owns `xwininfo`:
```
$ yay -F xwininfo
extra/xorg-xwininfo 1.1.5-3 (xorg-apps xorg) [installed]
    usr/bin/xwininfo
```
